# Generated by Django 3.0.6 on 2020-05-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=30)),
                ('objective', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[('ACTIVE', 0), ('ASSIGNED', 1), ('CLOSED', 2)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeadHunterOfferUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('headhunter_id', models.IntegerField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headhunter_offer', to='api_offers.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHeadHunterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headhunter_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offer', to='api_offers.Offer')),
            ],
        ),
    ]
